package restoreapplication.Telas;

import java.math.BigDecimal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import restoreapplication.Model.ExtratoProduto;
import restoreapplication.DAO.ExtratoProdutoDAO;
import restoreapplication.DAO.ProdutoDAO;
import restoreapplication.Model.Produto;

public class Verifica extends javax.swing.JFrame {

    boolean interromper = false;
    String empresa;
    String almox;

    public Verifica() {
        initComponents();
    }
    public Verifica(String empresaP, String almoxP) {
        initComponents();
        empresa = empresaP;
        almox = almoxP;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jProgressBar1 = new javax.swing.JProgressBar();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Verificando extrato de produtos com erro");
        setResizable(false);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("VERIFICA DIVERGENCIAS NO EXTRATO DO PRODUTO QUANDO O SALDO ESPERADO É DIFERENTE\nDO SALDO CALCULADO.\n");
        jScrollPane1.setViewportView(jTextArea1);

        jTextField2.setEditable(false);
        jTextField2.setBorder(javax.swing.BorderFactory.createTitledBorder("Codigo"));

        jButton1.setText("Verificar extrato dos produtos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancelar)
                .addGap(9, 9, 9))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        carregaProdutos();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        interromper = true;
        jTextArea1.append("PROCESSO INTERROMPIDO \n");
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Verifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Verifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Verifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Verifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Verifica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
public void carregaProdutos() {
        Thread thread = new Thread() {
            @Override
            public void run() {
                jTextArea1.append("PRODUTOS COM ERRO NAS MOVIMENTAÇÕES DO EXTRATO EMP: "+empresa+" ALMOX: "+almox+"\n");
                ProdutoDAO produtoDAO = new ProdutoDAO();
                ArrayList<Produto> listaProdutos = new ArrayList();
                try {
                    listaProdutos = produtoDAO.buscaCodigos(empresa);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Verifica.class.getName()).log(Level.SEVERE, null, ex);
                }
                int tamanho;
                tamanho = listaProdutos.size();
                jProgressBar1.setMaximum(tamanho);
                jProgressBar1.setMinimum(0);
                int indice = 0;
                int erros = 0;
                //ArrayList<ExtratoProduto> extratoDoProdutoERROS = new ArrayList();
                
                for (Produto prod: listaProdutos) {
                    if (interromper) {
                        break;
                    }
                    String codString = prod.getCODIGO();
                    
                    indice++;
                    jTextField2.setText(codString);
                    jProgressBar1.setValue(indice);
                    ExtratoProdutoDAO extratoProdutoDAO = new ExtratoProdutoDAO();
                    ArrayList<ExtratoProduto> extratoDoProduto = new ArrayList();
                    
                    try {
                        extratoDoProduto = extratoProdutoDAO.extratoProduto(empresa, almox, codString);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(Verifica.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    //float saldoAnterior = 0;
                    BigDecimal saldoAnterior = new BigDecimal("0");
                    for (ExtratoProduto produto : extratoDoProduto) {
                        BigDecimal qtd = new BigDecimal(produto.getQTDE());
                        BigDecimal saldoAtual = new BigDecimal(produto.getSALDO());
                        BigDecimal saldoEsperado = new BigDecimal("0");
                        if (produto.getENTRADASAIDA().equals("E")) {
                            saldoEsperado = saldoAnterior.add(qtd);
                            saldoAnterior = saldoAnterior.add(qtd);
                        } else {
                            saldoEsperado = saldoAnterior.subtract(qtd);
                            saldoAnterior = saldoAnterior.subtract(qtd);
                        }
                        String saldoEsperadoString = saldoEsperado.toString();
                        String saldoAtualString = saldoAtual.toString();
                        
                        if (!saldoEsperadoString.equals(saldoAtualString)) {
                            String descricao = MontaDescricao(produto.getMOVIMENTOID(),produto.getENTRADASAIDA());
                            //extratoDoProdutoERROS.add(produto);
                            jTextArea1.append("-----------------------------------------------------------"  + "\n");
                            jTextArea1.append("Produto        : " + produto.getPRODUTO() + "\n");
                            jTextArea1.append("Saldo atual    : " + saldoAtual +  "\n");
                            jTextArea1.append("Saldo esperado : " + saldoEsperado + "\n");
                            jTextArea1.append("Descrição      : " + descricao+ "\n");
                            jTextArea1.append("Data           : " + produto.getDATAHORA() + "\n");
                            
                            erros++;
                            jTextArea1.setCaretPosition(jTextArea1.getText().length());
                            break;
                        }
                        saldoAnterior = saldoAtual;
                    }
                    

                }
                //for (ExtratoProduto produto : extratoDoProdutoERROS) {
                //    SimpleDateFormat formato = new SimpleDateFormat("yyyy-mm-dd HH:mm:ss.SSSS"); 
                //    String dataString = produto.getDATAHORA();
                //    try {
                //        Date data = formato.parse(dataString);
                //    } catch (ParseException ex) {
                //        Logger.getLogger(Verifica.class.getName()).log(Level.SEVERE, null, ex);
                //    }
                //}
                jTextArea1.append("-----------------------------------------------------------"  + "\n");
                jTextArea1.append("PROCESSO CONCLUIDO.\n");
                jTextArea1.append("-----------------------------------------------------------"  + "\n");
                jTextArea1.append(erros + " - PRODUTOS COM ERRO.\n");
                jTextArea1.append("-----------------------------------------------------------"  + "\n");
                jTextArea1.setCaretPosition(jTextArea1.getText().length());
            }
        };

        thread.start();

    }

    public String MontaDescricao(String id,String es){
        String descricaoOperacao = "";
            if (id.equals("01") && es.equals("S")) {
                descricaoOperacao = "01 - S - VENDA DE MERCADORIA";
            }
            if (id.equals("01") && es.equals("E")) {
                descricaoOperacao = "01 - E -CANCELAMENTO DE VENDA DE MERCADORIA";
            }
            if (id.equals("02") && es.equals("E")) {
                descricaoOperacao = "02 - E - COMPRA DE MERCADORIA";
            }
            if (id.equals("02") && es.equals("S")) {
                descricaoOperacao = "02 - S - CANCELAMENTO COMPRA DE MERCADORIA";
            }
            if (id.equals("03")) {
                descricaoOperacao = "03 - S - TRANSFERENCIA ENTRE ALMOXARIFADO";
            }
            if (id.equals("04")) {
                descricaoOperacao = "04 - S - TRANSFERENCIA PRODUTO";
            }
            if (id.equals("05")) {
                descricaoOperacao = "05 - E - INVENTARIO";
            }
            if (id.equals("06")) {
                descricaoOperacao = "06 - S - RETIRADA";
            }
            if (id.equals("07") && es.equals("E")) {
                descricaoOperacao = "07 - E - DEVOLUÇÃO DE VENDA";
            }
            if (id.equals("07") && es.equals("S")) {
                descricaoOperacao = "07 - S - CANCELAMENTO DE DEVOLUÇÃO DE VENDA";
            }
            if (id.equals("08")) {
                descricaoOperacao = "08 - TRANSFERENCIA ENTRE FILIAIS";
            }
            if (id.equals("09") && es.equals("S")) {
                descricaoOperacao = "09 - S - DEVOLUÇÃO DE COMPRA";
            }
            if (id.equals("09") && es.equals("E")) {
                descricaoOperacao = "09 - E - CANCELAMENTO DE DEVOLUÇÃO DE COMPRA";
            }
            if (id.equals("10")) {
                descricaoOperacao = "10 - ORDEM DE PRODUÇAO";
            }
            return descricaoOperacao;
    }
}
